- name: ansible log file
  file: path=/tmp/.ansible state=directory

- name: Manually update packages list (Hack)
  apt: update_cache=True
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Manually update packages list (Hack)
  yum: update_cache=True
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_vars: "vars/{{ ansible_os_family }}.yml"

- name: pyenv dependencies
  package: name={{ item }} state=latest
  with_items:
    - "{{ pyenvdep }}"

- name: install the latest version of git
  package: name=git state=latest

- name: install pyenv
  git: repo=https://github.com/yyuu/pyenv.git
       dest=~/.pyenv
  become: no

- name: install pyenv-virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git
       dest=~/.pyenv/plugins/pyenv-virtualenv
  become: no

# FIXME prevent to execute twice if already done
- name: set environment variables
  shell: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  args:
    creates: /tmp/.ansible/pyenv_env
  become: no
